### ISSUE TITLE
Extract Promise utils into own library

### ISSUE THREAD

**Issue by martinheidegger** [consento-org/crypto#9]
The promise utils in this library ([`abort.ts`](https://github.com/consento-org/crypto/blob/e34325a823e947835438677e1c2a558cbe6026c9/src/util/abort.ts), [`extPromise.ts`](https://github.com/consento-org/crypto/blob/e34325a823e947835438677e1c2a558cbe6026c9/src/util/extPromise.ts), [`isPromiseLike.ts`](https://github.com/consento-org/crypto/blob/a894930fed6e2fee0187799d615d9247425ac51f/src/util/isPromiseLike.ts), [`toPromise`](https://github.com/consento-org/crypto/blob/a894930fed6e2fee0187799d615d9247425ac51f/src/util/toPromise.ts)) are useful, but it would be better if they were a standalone, documented library - specially since #6 will likely make them unused in `@consento-org/crypto` itself but keep them relevant for `@consento-org/api` or the mobile app.

Note: its perfectly for this to be an external repository.

**Comment by RangerMauve** [comment]
Are utils like is-object needed to be implemented in Consento? We might be able use something that already exists. Should I maybe name it `consento-utils`?

**Comment by RangerMauve** [comment]
Progress here: Does this look good so far? Should I abstract the buffer utils into there too? https://github.com/consento-org/promise-utils

**Comment by martinheidegger** [comment]
It looks good for a start, how about the naming, do you think
"promise-helpers" or "promise-workflow" might be a better name? The buffer
methods also probably belong to another (new?) Repo? Do you have npm
publish rights?

**Comment by RangerMauve** [comment]
I like promise-helpers as a name, promise-workflow seems kinda weird. Is there a particular thing about promise-utils that's confusing?

How do you feel about a general `consento-utils` repo that has all the utils in once place instead of spreading them out?

**Comment by martinheidegger** [comment]
The thing about utils is coming from this train of thought _(just picked randomly a few articles on the topic)_: [[1]](https://dave.cheney.net/2019/01/08/avoid-package-names-like-base-util-or-common), [[2]](https://www.adam-bien.com/roller/abien/entry/util_packages_are_evil), [[3]](https://softwareengineering.stackexchange.com/questions/284799/semantically-more-appropriate-package-name-than-util-for-the-following-things) - I tend to call those packages also `lang` instead of `utils` as to point out that these are packages that deal with the general language shortcomings. Aside from this `@consento/util` suggests that these only apply to consento specific code while I still belive that `promise-utils` are general purpose, useful even outside of the consento context.

**Comment by RangerMauve** [comment]
There's already a promise-utils package. :P

Would it maybe make sense to reuse some existing packages for all this stuff instead of adding a bunch of consento-maintained ones?

**Comment by martinheidegger** [comment]
There are 13000 npm packages  of I am not sure which projects would be good hosts for the code. I obviously would love it, if that code pieces could be accepted by bluebirdjs - most well known. The of the 44 i found on abort-support none really seemed to follow a similar code metapher. (almost all implementations added a `.cancel` operation which is rightfully deprecated by bluebirdjs). Do you think there is a way how we could get that in a project that would enjoy that?

To make the naming conversation simpler: How about using `@consento/promise` for the time being?

**Comment by RangerMauve** [comment]
Sounds good to me! 😁 Also `@consento/isObject` and `@consento/exists` and `@consento/buffer`?

**Comment by martinheidegger** [comment]
I feel like the other utils might have an easier time to find a package that match. 😉 

> Do you have npm publish rights?

**Comment by RangerMauve** [comment]
I'm not on the consento NPM yet. :o My username on there is rangermauve. I guess we can figure out replacement libs for the other utils later.

**Comment by martinheidegger** [comment]
@RangerMauve invitation sent.

**Comment by RangerMauve** [comment]
Before I add the utils in, mind taking a look at the `main` branch? 
[I replaced](https://github.com/consento-org/promise/commit/fc9f8d4ced6cb38326470f522fc939d4a916f24b) the `isObject` and `exists` dependencies with https://github.com/sindresorhus/is

**Comment by martinheidegger** [comment]
In typescripts strict mode there is a clear difference between objects that may be null and that may not. `exists` is used to turn an optional typed null or undefined object into a defined one. using the [is](https://www.typescriptlang.org/docs/handbook/advanced-types.html#user-defined-type-guards) type guard system of typescript.

```typescript
function foo (bar?: string): string {
  return bar + 'x' // Error because bar could be null/undefined 
}
function baz (bar?: string): string {
  return exists(bar) ? bar + 'x' : 'x' // Works because exists has the "is" operator in the declaration
}
function bazBlock (bar?: string): string {
  if (!exists(bar)) {
    return 'x'
  }
  // after this typescript is SURE that bar can not be null/undefined
  return bar + 'x'
}
```

What is a good shortcut in `is` that does the same thing? `is.existing`?

**Comment by RangerMauve** [comment]
Cool, I'll extract existing into its own thing, then. 😁

**Comment by RangerMauve** [comment]
Actually, does the [is.nullOrUndefined](https://github.com/sindresorhus/is/blob/master/source/index.ts#L182) method serve this purpose?

I currently have something like `const exists = (value) => !is.nullOrUndefined(value)`

**Comment by martinheidegger** [comment]
Published as https://github.com/consento-org/promisewith documentation [here](https://qiita.com/martinheidegger/items/3e6355e96e85fc1c841e)
